# Generated by Django 4.1 on 2022-09-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50)),
                ('cemail', models.EmailField(max_length=254)),
                ('csubject', models.CharField(max_length=50)),
                ('cmessage', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='my_skill',
            name='datetime',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='my_skill',
            name='dese',
            field=models.TextField(blank=True, max_length=509),
        ),
        migrations.AlterField(
            model_name='my_skill',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='my_skill',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
